<testsuite errors="1" failures="0" name="first_selenium.As a user I want to test the login functionality" skipped="0" tests="2" time="7.167363"><testcase classname="first_selenium.As a user I want to test the login functionality" name="Login to the demo website" status="passed" time="3.308778"><system-out>
<![CDATA[
@scenario.begin
  Scenario: Login to the demo website
    Given the user is on login page ... passed in 0.045s
    When the user enters the credentials and logs in ... passed in 3.258s
    Then he should land on the correct page ... passed in 0.006s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
Landed on correct login page
Landed on correct page

]]>
</system-out></testcase><testcase classname="first_selenium.As a user I want to test the login functionality" name="Navigate to user profile page" status="failed" time="3.858584"><error message="Message: Unable to locate element: Edit this page&#10;" type="NoSuchElementException">
<![CDATA[
Failing step: Then he should land on the correct profile page ... failed in 0.040s
Location: features\first_selenium.feature:11
Traceback (most recent call last):
  File "c:\program files\python36\lib\site-packages\behave\model.py", line 1456, in run
    match.run(runner.context)
  File "c:\program files\python36\lib\site-packages\behave\model.py", line 1903, in run
    self.func(context, *args, **kwargs)
  File "features\steps\reusableSteps.py", line 48, in step_impl
    if hm.element(context,"ProfilePage","editProfilelink").is_displayed():
  File "E:\Python-SeleniumFramework\python_behave_Framework\features\support\helperMethods.py", line 45, in element
    return context.browser.find_element(byType, val)
  File "c:\program files\python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 784, in find_element
    'value': value})['value']
  File "c:\program files\python36\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 249, in execute
    self.error_handler.check_response(response)
  File "c:\program files\python36\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 194, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchElementException: Message: Unable to locate element: Edit this page


Captured stdout:
Landed on correct login page
]]>
</error><system-out>
<![CDATA[
@scenario.begin
  Scenario: Navigate to user profile page
    Given the user is on dashboard page ... passed in 0.005s
    When user clicks the user profile icon ... passed in 3.814s
    Then he should land on the correct profile page ... failed in 0.040s

@scenario.end
--------------------------------------------------------------------------------

Captured stdout:
Landed on correct login page

]]>
</system-out></testcase></testsuite>